### ISSUE TITLE
Plan for Redmine 3.x.x

### ISSUE THREAD

**Issue by hmkim** [edosoft/redmine-inherit-fields-plugin#10]
Do you have release plan with Redmine 3.x.x version?

Thanks in advance!

**Comment by jvreeken** [comment]
I would love to know if this can be made compatible with 3.x.x of redmine too!

**Comment by davidverdu** [comment]
We have the intention to release it probably on next year. If you make changes or tests to current code we will check them and add to the repository. Thanks for your interest

**Comment by davidverdu** [comment]
The plugin works now for Redmine 3.x.x, you can check it out

**Comment by hmkim** [comment]
Thanks for your support. I'll check it (test).
