### ISSUE TITLE
Error page with configuration

### ISSUE THREAD

**Issue by hmkim** [edosoft/redmine-inherit-fields-plugin#11]
![2015-12-17 14 23 45](https://cloud.githubusercontent.com/assets/4966343/11862192/77409812-a4cb-11e5-9b8f-99cab4928165.png)

When I click the config button, I got the error.

![2015-12-17 14 23 41](https://cloud.githubusercontent.com/assets/4966343/11862196/846318a8-a4cb-11e5-8a1d-49070f8b7ed8.png)

How can I handle this error?

please check this.

**Comment by davidverdu** [comment]
Have you installed the plugin with the correct folder name? It should be redmine_subtasks_inherited_fields. Please follow the installation instructions carefully.

**Comment by MichaelZahar** [comment]
Thx! It helps me.
