### ISSUE TITLE
Subject 

### ISSUE THREAD

**Issue by AlessandroZucchi** [edosoft/redmine-inherit-fields-plugin#12]
Hi, 
Is it possible ad subject field to the option? 
It's very useful for me copy the subject from
 the parent to the child. 

Thank you
Alessandro

**Comment by davidverdu** [comment]
Hi Alessandro,

we will take into account your requirement when we update the plugin.

Thank you!

**Comment by AlessandroZucchi** [comment]
OK, thanks.

Have you got an idea on release date ?



Alessandro







>>> David Verdú <notifications@github.com> 11/02/2016 9.40 >>>

 
Hi Alessandro,

we will take into account your requirement when we update the plugin.

Thank you!

-

**Comment by davidverdu** [comment]
I don't know yet. We are full of work. We also accept pull requests and sponsorships.

Thank you!

**Comment by davidverdu** [comment]
Solved. Thank you t-gergely
