### ISSUE TITLE
issue field inherit from project

### ISSUE THREAD

**Issue by biohazardxxx** [edosoft/redmine-inherit-fields-plugin#15]
Hi,
great plugin thanks!
We have custom field at project and same on issue level. THis would be a great enhancement:
When there is the same custom field (name and type) setup on project as on issue level then the value would be inherited for new issues in the project.
Please let me knwo if you have questions.

Best regards
-Bio

**Comment by davidverdu** [comment]
Hello. The plugin currently supports inheriting issue custom fields from parent issue to subtasks. Inheriting project custom field to issue custom field of the same name is not implemented but It could be considered. Could you confirm me that this is what you want? If you have developed this functionality on your own you can PR.

**Comment by oscar-renteria** [comment]
Hi, 

is this feature implemented?

Regards,
Óscar

**Comment by davidverdu** [comment]
Hello. No, is not implemented.
