### ISSUE TITLE
Automatic update for task and subtasks already created

### ISSUE THREAD

**Issue by AhmedDAMMAK85** [edosoft/redmine-inherit-fields-plugin#16]
Hi,
**Thank you for the plugin Good Job.** 
For an existing parent task and subtasks there are no automatic update. That mean when i modify the parent task, normally the subtask inherit the modification automatically.
Auto_cascade
Regards,
Ahmed

**Comment by klyonrad** [comment]
Honestly I suggest to reject this feature request. For editing properties of multiple issues Redmine offers the bulk edit feature

**Comment by davidverdu** [comment]
For the moment this proposed featured is not in the Roadmap. As Klyonrad says, you can use bulk edit for that
