### ISSUE TITLE
Settings page broken?

### ISSUE THREAD

**Issue by klyonrad** [edosoft/redmine-inherit-fields-plugin#19]
when I attempt to save the settings they do not show up anymore at the settings page.

The defaults are shown correctly, but when something is saved in the database it is broken.

This is observed with Redmine 3.4

I read the [Redmine Plugin Tutorial](http://www.redmine.org/projects/redmine/wiki/Plugin_Tutorial) and saw that the recommendation for accessing the settings in the partial is different: not with symbols but with strings as keys.

So changing everything like this fixes it:

```ruby

<p>  
  <label><%= l(:inherit_fixed_version) %></label>
  <%= check_box_tag 'settings[inherit_fixed_version_id]', 1, @settings['inherit_fixed_version_id'] %>
</p>

```

can someone confirm this?

**Comment by aozhi2nd** [comment]
not work

**Comment by davidverdu** [comment]
Solved!
