### ISSUE TITLE
the settings lost in 3.4.x

### ISSUE THREAD

**Issue by aozhi2nd** [edosoft/redmine-inherit-fields-plugin#24]
in redmine 3.4.x , 
select a few fields to inherit 
click apply ,but the settings lost

**Comment by 0l3er** [comment]
Same problem

**Comment by levneploh** [comment]
same with 3.4.6.stable

**Comment by realMaxA** [comment]
+1

**Comment by ramlez** [comment]
+1

**Comment by vphantom** [comment]
Note: this seems to be a duplicate of #19, which contains a possible fix.

**Comment by michaelliu1213** [comment]
> in redmine 3.4.x ,
> select a few fields to inherit
> click apply ,but the settings lost

try this fork, it's worked in in redmine 3.4.2 
```
git clone https://github.com/dkd/redmine-inherit-fields-plugin redmine_subtasks_inherited_fields
```

**Comment by davidverdu** [comment]
This isssue has been solved thanks to a contribution
