### ISSUE TITLE
Installation on CentOS 7

### ISSUE THREAD

**Issue by ciakval** [edosoft/redmine-inherit-fields-plugin#25]
On CentOS 7 with SElinux enabled, installation of this plugin includes additional steps.

When the plugin is installed according to the documentation, application startup fails. The problem (analyzed by running with "PassengerFriendlyErrorPages on") is that the plugin wants to copy file 

_$REDMINEDIR/plugins/redmine_subtasks_inherited_fields/assets/javascripts/subtasks_inherited_fields.js_

to

_$REDMINEDIR/public/plugin_assets/redmine_subtasks_inherited_fields/javascripts_,

which is prevented by SElinux.

The solution is to create the directories and copy the file manually, then restoring ownership, file modes and SElinux context.

```
cd $REDMINEDIR

mkdir -pv public/plugin_assets/redmine_subtasks_inherited_fields/javascripts

cp plugins/redmine_subtasks_inherited_fields/assets/javascripts/subtasks_inherited_fields.js public/plugin_assets/redmine_subtasks_inherited_fields/javascripts

chown -R apache:apache public/plugin_assets/redmine_subtasks_inherited_fields/javascripts
chmod -R 755 public/plugin_assets/redmine_subtasks_inherited_fields/javascripts
restorecon -RvF public/plugin_assets/redmine_subtasks_inherited_fields/javascripts
```

**Comment by davidverdu** [comment]
Thank you for your notes! I'm sure it will be useful for systems using SElinux
