### ISSUE TITLE
Missing template plugin.html.erb of the config page

### ISSUE THREAD

**Issue by zanzotti** [edosoft/redmine-inherit-fields-plugin#26]
Installed the right branch 2,5x in 2.3.6-0 redmine, **do not show the config page**.

Log message (opt/redmine-2.6.3-0/apps/redmine/htdocs/log/production.log)

[root@shlv-cas01 log]# tail -f production.log
  Rendered layouts/base.html.erb (745.5ms)
Completed 200 OK in 772.7ms (Views: 725.6ms | ActiveRecord: 42.3ms)
Started GET "/redmine/settings/plugin/redmine_subtasks_inherited_fields" for 172                                                                                                 .31.0.71 at 2018-06-25 13:39:54 -0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_subtasks_inherited_fields"}
  Current user: Marcelo (id=28)
  Rendered plugins/scrum2b/app/views/settings/plugin.html.erb within layouts/adm                                                                                                 in (6.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.3ms)
Completed 404 Not Found in 516.0ms (Views: 458.7ms | ActiveRecord: 41.7ms)

Accepting suggestions...

**Comment by davidverdu** [comment]
Please follow the git clone command as it's explained in installation instructions, not just a simple git clone.
