### ISSUE TITLE
Inherit Parameters when Create and Continue is pressed

### ISSUE THREAD

**Issue by darioo** [edosoft/redmine-inherit-fields-plugin#5]
When I create subtask from main task with Create and Continue button, new form haven't got preselected fields. Form me this is limitation for using this plugin.

**Comment by lublasco** [comment]
Hi, David:

I'm using your plugin in a Redmine 3.1 installation and it works fine.

But I would need this very feature too: 
>When I create subtask from main task with Create and Continue button, new form haven't got preselected fields. For me this is limitation for using this plugin.

Is there a possibility you can update the plugin with this feature?

Thanks in advance for an awesome plugin!

**Comment by davidverdu** [comment]
This feature is going to be implemented soon

**Comment by davidverdu** [comment]
This is the User Story that is going to be implemented:

USER STORY Inherit fields on Create and Continue
GIVEN I have this plugin installed and configured to inherit some fields
    AND I have a project with at least an Issue named "Parent"
    AND that issue have "parent task" field enabled for its tracker
WHEN I go to the Issue page
   AND I press Add subtask
   AND I see the create child issue form with configured parent fields inherited
   AND I see in the field "parent task" the issue ID of the "Parent" issue
   AND I fill in the not inherited fields
   AND I press "Create and Continue" button
THEN the child issue named "child1" is created for this "Parent"
   AND a new create child issue form is shown with configured inherited fields filled in again
   AND the new form has "Parent" ID in "Parent task" field, so it's going to be created as a new "Parent" child
   AND 
       IF I then fill in the not inherited fields 
           AND I Press "Create and Continue" button again, 
       THEN this issue "child2" will be created as a child of "Parent"
           AND "child1" and "child2" will be siblings of the same parent
           AND I new create child form will be shown with inherited fields filled in again

**Comment by davidverdu** [comment]
Already implemented. Thanks to [Luis Blasco](http://www.luisblasco.com) for his contribution to implement this feature. Now the plugin has two branches: master for Redmine 3.x.x and 2.5.x for older Redmine versions

**Comment by lublasco** [comment]
Great work, David!

Thank you very much.

**Comment by davidverdu** [comment]
You are very wellcome
