### ISSUE TITLE
Inherit From Project

### ISSUE THREAD

**Issue by laytoneverson** [edosoft/redmine-inherit-fields-plugin#9]
I am researching your plugin and wonder if this plugin will allow you to inherit values from the project itself. We use a custom field that carries a project id throughout our issues as well as time entries. Here are some user stories.

As a project manager I create a new project with a custom field named "Project Id" and enter the appropriate value.

As a project manager I am able to create a task directly below the project and that will inherit the configured parameters from the project.

As a developer I add a time entry to a task. The task automatically inherits configured parameters from the task.

Thank you for your contribution!

**Comment by aitorcarrera** [comment]
Hi Layton!

I'll past your request to the team. take into consideration to contribute yourself to the project with a PR. In oder hand if your company is looking other for redmine customization, let m know, maybe we can collaborate in that way.

Best regards.

**Comment by davidverdu** [comment]
Hi Layton. At the moment the only inheritance occurs from parent task to task. There is no inheritance from custom project fields to custom task fields but off course it could be considered as a plugin enhancement. 

Thank you for your request!

**Comment by laytoneverson** [comment]
I wish I was a ruby dev. :D
